<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="bepelManufacturerServiceWSDLWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/bepelManufacturerServiceWSDLWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/bepelManufacturerServiceWSDLWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://service.soen487/">
    <import location="bepelManufacturerServiceWSDL.wsdl" namespace="http://service.soen487/"/>
    <plnk:partnerLinkType name="bepelManufacturerServiceLinkType">
        <plnk:role name="bepelManufacturerServiceRole" portType="ns:bepelManufacturerService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="bepelManufacturerServiceLinkType2">
        <plnk:role name="bepelManufacturerServiceRole" portType="ns:bepelManufacturerService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="bepelManufacturerServiceLinkType3">
        <plnk:role name="bepelManufacturerServiceRole" portType="ns:bepelManufacturerService"/>
    </plnk:partnerLinkType>
</definitions>
