<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="XMLReaderWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/XMLReaderWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/XMLReaderWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://service.soen487/">
    <import location="XMLReader.wsdl" namespace="http://service.soen487/"/>
    <plnk:partnerLinkType name="ReaderWsLinkType">
        <plnk:role name="ReaderWsRole" portType="ns:ReaderWs"/>
    </plnk:partnerLinkType>
</definitions>
